import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>블로그 버전 1.00</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>블로그 만들기 도전</h1>
      </main>
    </>
  );
}
