import Head from "next/head";
import Link from "next/link";
import { format, parseISO, formatDistance, subDays } from "date-fns";
import { getAllPosts } from "../lib/data";

export default function Home({ posts }) {
  console.log(posts);
  return (
    <>
      <Head>
        <title>블로그 버전 1.00</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>블로그 만들기 도전</h1>

        <div>
          {posts.map((item) => (
            <PostListItem key={item.slug} {...item} />
          ))}
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const allPosts = getAllPosts();
  return {
    props: {
      posts: allPosts.map(({ data, content, slug }) => ({
        ...data,
        date: data.date.toString(),
        content,
        slug,
      })),
    },
  };
}

function PostListItem({ slug, title, date, content }) {
  return (
    <div>
      <div>
        <Link href={`/blog/${slug}`}>
          <a>{title}</a>
        </Link>
      </div>
      <div>{date}</div>
      <div>
        {formatDistance(subDays(new Date(), 13), new Date(), {
          addSuffix: true,
        })}
      </div>
      <div>{content.substr(0, 300)}</div>
    </div>
  );
}
